### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'package-lock.json'

### ISSUE THREAD

**Issue by NaseerMohammedAbdul** [c-hive/gha-npm-cache#9]
when I use this library, I see the GitHub Action failed with this error. please help me on this. 

/usr/bin/uname
Linux
/opt/hostedtoolcache/node/14.17.1/x64/bin/npm config get cache
/home/runner/.npm
**Error: Error: ENOENT: no such file or directory, open 'package-lock.json'**

**Comment by thisismydesign** [comment]
The lock file has to be in the project root

**Comment by mdentremont** [comment]
@thisismydesign I just had this happen in my repository as well -- nothing has really changed since the last successful run, but I do see that 1.1.0 was deployed.

My package-lock.json is inside of my working directory as specified here (I excluded the folder name as it isn't important:
![image](https://user-images.githubusercontent.com/1106324/132006483-23f28756-372e-4c9d-9059-3c5ddece8ab4.png)

This change caused the breakage: https://github.com/c-hive/gha-npm-cache/commit/a61971759680fae1cc7c992c27d769f88cbf6cb7

Maybe a change could be introduced which doesn't use `./` if a directory parameter isn't provided? This would use the working directory by default which I believe is correct.

**Comment by thisismydesign** [comment]
@mdentremont Interesting, thanks for reporting. So `working-directory` applies to `uses` steps as well not only for `run`? This is not obvious to me from the docs https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun In fact, it looks more like a bug / misuse.

I will test it and get back to you. Also maybe this is possible to use on the action directly, making the `directory` option obsolete.

**Comment by thisismydesign** [comment]
@mdentremont I recommend that you use the `directory` option as that is the intended way and other actions work the same way. The run defaults should only apply to `run`. 

That said, I opened a new issue for supporting the old approach: https://github.com/c-hive/gha-npm-cache/issues/12
